name: My First Workflow

on: [push]

# jobs:
#   my-job:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Hello, World!"
#       - run: ${{ secrets.HELLO }}
#   build: 
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Building..."
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Testing..."

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 21.x, 22.x]
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm test